### ISSUE TITLE
No module named keras_resnet

### ISSUE THREAD

**Issue by 123liluky** [kocurvik/retinanet_traffic_3D#4]
Hi, when I run python dataset_utils/test.py, error happens:
File "dataset_utils/../keras_retinanet/models/resnet.py", line 19, in <module>
 import keras_resnet
ModuleNotFoundError: No module named 'keras_resnet'

**Comment by kocurvik** [comment]
Hello,

you need to install it as a separate package either using conda:

`conda install -c conda-forge keras-resnet`

or pip:

`pip install keras-resnet`

**Comment by 123liluky** [comment]
Thanks for your reply!

**Comment by 123liluky** [comment]
Hi, I renamed BrnoCompSpeed.tar.0 as BrnoCompSpeed.tar, and then untar it. It's OK.
But when I try to untar other three tar files, error happens.
My directory is like below:
![image](https://user-images.githubusercontent.com/20832778/153141682-3a17b8c5-31a7-4138-b715-dbe82def9d41.png)

**Comment by kocurvik** [comment]
I would recommend trying something like [this](https://askubuntu.com/questions/1179657/how-to-extract-tgz-part)
